### ISSUE TITLE
Permission change needed on root ssk priv key

### ISSUE THREAD

**Issue by acoderninja** [Link-/ansible_lab#1]
Hi Bassem,

First of all thank you for this sharing. I was looking for a sweet and simple setup for ansible using docker and found it great.
During my testing I found the permission issue and after I set the permission from 644 to 600, it worked.

[root@d9e982a1a472 .ssh]# ls -lrt
total 8
-rw-r--r-- 1 root root 3381 Jul 25 03:46 id_rsa
-rw-r--r-- 1 root root  383 Jul 25 03:52 known_hosts
[root@d9e982a1a472 .ssh]#
[root@d9e982a1a472 .ssh]#
[root@d9e982a1a472 .ssh]# chmod 600 id_rsa
[root@d9e982a1a472 .ssh]#
 
Hope this is helpful for others too.

**Comment by Link-** [comment]
Hey @acoderninja thank you for your feedback and for using this! 

This is great input, I think it'll be great to have this instruction in the Dockerfiles. Do you have the capacity to create a PR with these changes?

**Comment by acoderninja** [comment]
Yeah Sure, will do.

**Comment by Link-** [comment]
Fixed in #2
